### ISSUE TITLE
Meteor TS Example

### ISSUE THREAD

**Issue by daslicht** [nodets/meteor-typescript#1]
Hi,
is there somewhere an example using TS with Meteor to get started please ?
Cheers Marc

**Comment by kataras** [comment]
Yes of course, it is simple and I started used this example to show how to connect mysql with meteor js ( I also publish a package named: nodets:mysql), it's easy. Just meteor add nodets:mysql, define the typings( or definitions folder) with your d.ts files and write code with .ts and .tsx ( for react) , meteor will auto compile the files to javascript, https://github.com/nodets/node-mysql-wrapper/tree/master/examples_meteorjs_typescript

**Comment by daslicht** [comment]
Thank you !
I didnt even know that you can use Meeor with MySQL! nice.
Do you think its better to get started with Meteor without TypeScript ?
I have some experience with Meteor (I followed Discover Meteor)

**Comment by kataras** [comment]
Look, I stopped developing with meteor, I used meteor because of live/sync mono.collection object, but I though that I had to create a package for this purpose    for simple nodejs too, and I did it and I am continue developing this package named: mysql-live . Now I can have live database collections with nodejs as I had with meteorjs. Yes Mysql with Meteor can work with nodets:mysql :) . 

If you want to use meteor, you can easly work with typescript it is not a big deal, typescript can saves you in big projects, use typescript anywhere you can, and in meteorjs you can :)

**Comment by daslicht** [comment]
Interesting, I am not fixed to meteor as well and still unsure which to use.
Essentially I just look to simplyfy my current stack which is based on PHP: FatFreeFramework + RedbeanPHP. By now I havent fond anything which would make those approach simpler :/

**Comment by kataras** [comment]
I could suggest you to use this development flow:

Frontend: ReactJS framework with ui style : bootstrap or material-ui with .less/.sass files, lodash library, jquery of course in some cases you still want it, mysql-live-client if you use mysql database, that's for a basic application.

Backend: Node js with expressjs,  mysql-live and socket.io.

and Typescript for all of them, I don't know if I helped you but trust me I worked with many frameworks and libraries, Now I know that Reactjs for frontend and Nodejs for backend is the faster,safer and most elegant way to develop application in 2015 :) 

I was java developer and asp.net c#, I was hated javascript now I am working everyday with this

**Comment by daslicht** [comment]
Yesterday I tried AngularJS 2 TS, it looks also promising. But its documentation is less good atm

**Comment by kataras** [comment]
Yes I worked with angular 1 and angular 2 too, I switch to ReactJS because angular 1 from angular 2 has a lot of changes, also it's good to know that in Angular 2 you have one-way- data binding like ReactJS ( they almost accepted that angular 1 was a shit for perfomane compared to ReactJS ) Angular is good if you want to start with something, many apps are build with Angular but I think that ReactJS will grow more than angular did :) , this is my opinion ofc

**Comment by daslicht** [comment]
Yeah alot is going on atm. 
Do you have any further examples docs tuts for me to get started with the stack you mentioned above please? 

I am going to try now *mysql-live*

**Comment by kataras** [comment]
Yes I have an example with webpack,typescript,bootstrap, socket.io, mysql-live server and client side but it just for start, it shows just a list of stories with real database changes when you change a story from your database managment application or anywhere, I will update it soon stay tuned :P it has got a bug on modules I have to use ./module.ts in order to webpack import it* look: https://github.com/nodets/react-typescript-fullstack-skeleton

**Comment by daslicht** [comment]
Yeah I saw that, Looks like its to much at the moment for me sicne I have nerby no experience with React , Gulp Redux Flux , TS.

I try to get Expressjs runing with TS and than addd mysql-live

**Comment by kataras** [comment]
Yes, you can watch a lot of tutorials in youtube for expressjs too, ( you can find lynda, pluralsight tutorials in other torre.... sites you know :P ) If you want any help let me know, we can talk at gitter too https://gitter.im/nodets/node-mysql-wrapper
